require("TurnToUpperCase")
--print(TurnToUpperCase())
-----------------------------------------
require("TwoNumberTogether")
--printTwoNumSum()
------------------------------------------
require("ManyNumberTogether")
--printUserSum()
------------------------------------------
require("RandomNumber1-Max")
